export * from "./hooks/useAdminDashboardInsights";
export * from "./hooks/useIsAdmin";
export * from "./hooks/useSession";

export { default as AdminLayout } from "./pages/AdminLayout";
export { default as AdminDashboardShell } from "./pages/AdminDashboardShell";
export { default as AdminDashboardOverview } from "./pages/AdminDashboardOverview";
export { default as AdminDashboardTracking } from "./pages/AdminDashboardTracking";
export { default as AdminDashboardQuotations } from "./pages/AdminDashboardQuotations";
export { default as AdminQuotations } from "./pages/AdminQuotations";
export { default as AdminQuotationsOverview } from "./pages/AdminQuotationsOverview";
export { default as AdminHome } from "./pages/AdminHome";
export { default as AdminProductsList } from "./pages/AdminProductsList";
export { default as AdminProductForm } from "./pages/AdminProductForm";
export { default as AdminCategoriesList } from "./pages/AdminCategoriesList";
export { default as AdminCategoryForm } from "./pages/AdminCategoryForm";
export { default as AdminOrders } from "./pages/AdminOrders";
export { default as AdminPages } from "./pages/AdminPages";
export { default as AdminCustomers } from "./pages/AdminCustomers";
export { default as AdminCoupons } from "./pages/AdminCoupons";
export { default as AdminBanners } from "./pages/AdminBanners";
export { default as AdminSettings } from "./pages/AdminSettings";
export { default as AdminSettingsLayout } from "./pages/AdminSettingsLayout";
export { default as AdminUsersAccess } from "./pages/AdminUsersAccess";
export { AdminSettingsFrete, AdminSettingsPagamentos, AdminSettingsIdentidade, AdminSettingsIntegracoes } from "./pages/AdminSettingsPlaceholder";
export { default as AdminTheme } from "./pages/AdminTheme";
export { default as AdminAiAnalysis } from "./pages/AdminAiAnalysis";
export { default as AdminIntelligence } from "./pages/AdminIntelligence";
export { default as AdminBulkImageSearch } from "./pages/AdminBulkImageSearch";
export { default as AdminStoreSelector } from "./pages/AdminStoreSelector";
export { default as AdminProductsImport } from "./pages/AdminProductsImport";
export { default as AdminProductScraper } from "./pages/AdminProductScraper";
export { default as AdminReviews } from "./pages/AdminReviews";
export { default as AdminPriceIntelligence } from "./pages/AdminPriceIntelligence";
export { default as AdminImageReview } from "./pages/AdminImageReview";
export { default as AdminAiReports } from "./pages/AdminAiReports";
export { default as AdminBatchOps } from "./pages/AdminBatchOps";
export { default as AdminRecommendations } from "./pages/AdminRecommendations";

// Payments / Gateway AllowPay
export { default as AdminPaymentsLayout } from "./pages/payments/AdminPaymentsLayout";
export { default as AdminPaymentsOverview } from "./pages/payments/AdminPaymentsOverview";
export { default as AdminPaymentsGateways } from "./pages/payments/AdminPaymentsGateways";
export { default as AdminPaymentsGatewayAdd } from "./pages/payments/AdminPaymentsGatewayAdd";
export { default as AdminPaymentsGatewayLogs } from "./pages/payments/AdminPaymentsGatewayLogs";
export { default as AdminPaymentsGatewayStatus } from "./pages/payments/AdminPaymentsGatewayStatus";
export { default as AdminPaymentsCheckouts } from "./pages/payments/AdminPaymentsCheckouts";
export { default as AdminPaymentsCheckoutCreate } from "./pages/payments/AdminPaymentsCheckoutCreate";
export { default as AdminPaymentsCheckoutTemplates } from "./pages/payments/AdminPaymentsCheckoutTemplates";
export { default as AdminPaymentsCheckoutWebhooks } from "./pages/payments/AdminPaymentsCheckoutWebhooks";
export { default as AdminPaymentsMethods } from "./pages/payments/AdminPaymentsMethods";
export { default as AdminPaymentsPix } from "./pages/payments/AdminPaymentsPix";
export { default as AdminPaymentsCard } from "./pages/payments/AdminPaymentsCard";
export { default as AdminPaymentsBoleto } from "./pages/payments/AdminPaymentsBoleto";
export { default as AdminPaymentsSplit } from "./pages/payments/AdminPaymentsSplit";
export { default as AdminPaymentsAntifraud } from "./pages/payments/AdminPaymentsAntifraud";
export { default as AdminPaymentsAntifraudRules } from "./pages/payments/AdminPaymentsAntifraudRules";
export { default as AdminPaymentsAntifraudScore } from "./pages/payments/AdminPaymentsAntifraudScore";
export { default as AdminPaymentsAntifraudBlacklist } from "./pages/payments/AdminPaymentsAntifraudBlacklist";
export { default as AdminPaymentsSubscriptions } from "./pages/payments/AdminPaymentsSubscriptions";
export { default as AdminPaymentsSubscriptionsPlans } from "./pages/payments/AdminPaymentsSubscriptionsPlans";
export { default as AdminPaymentsSubscriptionsClients } from "./pages/payments/AdminPaymentsSubscriptionsClients";
export { default as AdminPaymentsSubscriptionsRecurring } from "./pages/payments/AdminPaymentsSubscriptionsRecurring";
export { default as AdminPaymentsWebhooks } from "./pages/payments/AdminPaymentsWebhooks";
export { default as AdminPaymentsWebhookEvents } from "./pages/payments/AdminPaymentsWebhookEvents";
export { default as AdminPaymentsWebhookLogs } from "./pages/payments/AdminPaymentsWebhookLogs";
export { default as AdminPaymentsApi } from "./pages/payments/AdminPaymentsApi";
export { default as AdminPaymentsApiKeys } from "./pages/payments/AdminPaymentsApiKeys";
export { default as AdminPaymentsApiDocs } from "./pages/payments/AdminPaymentsApiDocs";
export { default as AdminPaymentsApiSandbox } from "./pages/payments/AdminPaymentsApiSandbox";
