-- Fix SKU conflict target compatibility for upsert(onConflict: 'sku')
-- Partial unique index cannot be inferred by ON CONFLICT (sku) generated by supabase-js.
DROP INDEX IF EXISTS public.store_products_sku_unique;

-- Regular unique index allows multiple NULLs and is compatible with ON CONFLICT (sku)
CREATE UNIQUE INDEX IF NOT EXISTS store_products_sku_unique
ON public.store_products (sku);